/* Automically generated by wasm2c */
#include <math.h>
#include <string.h>

#include "app_polluted.h"
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#define LIKELY(x) __builtin_expect(!!(x), 1)

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION)

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth

#define UNREACHABLE TRAP(UNREACHABLE)

#define CALL_INDIRECT(table, t, ft, x, ...)          \
  (LIKELY((x) < table.size && table.data[x].func &&  \
          table.data[x].func_type == func_types[ft]) \
       || TRAP(CALL_INDIRECT)                        \
       , ((t)table.data[x].func)(__VA_ARGS__))

#if WASM_RT_MEMCHECK_SIGNAL_HANDLER
#define MEMCHECK(mem, a, t)
#else
#define MEMCHECK(mem, a, t)  \
  if (UNLIKELY((a) + sizeof(t) > mem->size)) TRAP(OOB)
#endif

#if WABT_BIG_ENDIAN
static inline void load_data(void *dest, const void *src, size_t n) {
  size_t i = 0;
  u8 *dest_chars = dest;
  memcpy(dest, src, n);
  for (i = 0; i < (n>>1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[m.size - o - s]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                                                 \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {                            \
    MEMCHECK(mem, addr, t1);                                                          \
    t1 result;                                                                        \
    __builtin_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], sizeof(t1)); \
    return (t3)(t2)result;                                                            \
  }

#define DEFINE_STORE(name, t1, t2)                                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) {                 \
    MEMCHECK(mem, addr, t1);                                                           \
    t1 wrapped = (t1)value;                                                            \
    __builtin_memcpy(&mem->data[mem->size - addr - sizeof(t1)], &wrapped, sizeof(t1)); \
  }
#else
static inline void load_data(void *dest, const void *src, size_t n) {
  memcpy(dest, src, n);
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[o]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                        \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {   \
    MEMCHECK(mem, addr, t1);                                 \
    t1 result;                                               \
    __builtin_memcpy(&result, &mem->data[addr], sizeof(t1)); \
    return (t3)(t2)result;                                   \
  }

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) { \
    MEMCHECK(mem, addr, t1);                                           \
    t1 wrapped = (t1)value;                                            \
    __builtin_memcpy(&mem->data[addr], &wrapped, sizeof(t1));          \
  }
#endif

DEFINE_LOAD(i32_load, u32, u32, u32);
DEFINE_LOAD(i64_load, u64, u64, u64);
DEFINE_LOAD(f32_load, f32, f32, f32);
DEFINE_LOAD(f64_load, f64, f64, f64);
DEFINE_LOAD(i32_load8_s, s8, s32, u32);
DEFINE_LOAD(i64_load8_s, s8, s64, u64);
DEFINE_LOAD(i32_load8_u, u8, u32, u32);
DEFINE_LOAD(i64_load8_u, u8, u64, u64);
DEFINE_LOAD(i32_load16_s, s16, s32, u32);
DEFINE_LOAD(i64_load16_s, s16, s64, u64);
DEFINE_LOAD(i32_load16_u, u16, u32, u32);
DEFINE_LOAD(i64_load16_u, u16, u64, u64);
DEFINE_LOAD(i64_load32_s, s32, s64, u64);
DEFINE_LOAD(i64_load32_u, u32, u64, u64);
DEFINE_STORE(i32_store, u32, u32);
DEFINE_STORE(i64_store, u64, u64);
DEFINE_STORE(f32_store, f32, f32);
DEFINE_STORE(f64_store, f64, f64);
DEFINE_STORE(i32_store8, u8, u32);
DEFINE_STORE(i32_store16, u16, u32);
DEFINE_STORE(i64_store8, u8, u64);
DEFINE_STORE(i64_store16, u16, u64);
DEFINE_STORE(i64_store32, u32, u64);

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#define DIV_S(ut, min, x, y)                                 \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO)  \
  : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
  : (ut)((x) / (y)))

#define REM_S(ut, min, x, y)                                \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO) \
  : (UNLIKELY((x) == min && (y) == -1)) ? 0                 \
  : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x) op (y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
  : (x < y) ? x : y)

#define FMAX(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
  : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                             \
  ((UNLIKELY((x) != (x)))                        ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                 : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                            \
  ((UNLIKELY((x) != (x)))                       ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296.,  x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))         ? 0                           \
   : (UNLIKELY(!((x)minop(min)))) ? smin                        \
   : (UNLIKELY(!((x) < (max))))   ? smax                        \
                                  : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F32(x) TRUNC_SAT_S(u32, s32, f32, (f32)INT32_MIN, INT32_MIN, >=, 2147483648.f, INT32_MAX, x)
#define I64_TRUNC_SAT_S_F32(x) TRUNC_SAT_S(u64, s64, f32, (f32)INT64_MIN, INT64_MIN, >=, (f32)INT64_MAX, INT64_MAX, x)
#define I32_TRUNC_SAT_S_F64(x) TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., INT32_MAX, x)
#define I64_TRUNC_SAT_S_F64(x) TRUNC_SAT_S(u64, s64, f64, (f64)INT64_MIN, INT64_MIN, >=, (f64)INT64_MAX, INT64_MAX, x)

#define TRUNC_SAT_U(ut, ft, max, smax, x) \
  ((UNLIKELY((x) != (x)))        ? 0      \
   : (UNLIKELY(!((x) > (ft)-1))) ? 0      \
   : (UNLIKELY(!((x) < (max))))  ? smax   \
                                 : (ut)(x))

#define I32_TRUNC_SAT_U_F32(x) TRUNC_SAT_U(u32, f32, 4294967296.f, UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F32(x) TRUNC_SAT_U(u64, f32, (f32)UINT64_MAX, UINT64_MAX, x)
#define I32_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u32, f64, 4294967296., UINT32_MAX,  x)
#define I64_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u64, f64, (f64)UINT64_MAX, UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)  \
  static inline t2 name(t1 x) {           \
    t2 result;                            \
    memcpy(&result, &x, sizeof(result));  \
    return result;                        \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)


static u32 func_types[3];

static void init_func_types(void) {
  func_types[0] = wasm_rt_register_func_type(1, 0, WASM_RT_I32);
  func_types[1] = wasm_rt_register_func_type(0, 0);
  func_types[2] = wasm_rt_register_func_type(2, 0, WASM_RT_I32, WASM_RT_I32);
}

static void w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h0b8605991630ed23E(u32);
static void w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h9258f2dac55d64d2E(u32);
static void w2c_app(void);
static void w2c__ZN4core9panicking5panic17h3b99507adb69386aE(u32, u32);
static void w2c__ZN4core6result13unwrap_failed17h4ed86702351a3017E(u32);
static void w2c__ZN4core9panicking9panic_fmt17h5c7ce52813e94bcdE(void);
static void w2c_rust_begin_unwind(void);

static u32 w2c___stack_pointer;
static u32 w2c_DEVICE_PERIPHERALS;
static u32 w2c___data_end;
static u32 w2c___heap_base;

static void init_globals(void) {
  w2c___stack_pointer = 1048576u;
  w2c_DEVICE_PERIPHERALS = 1048616u;
  w2c___data_end = 1048617u;
  w2c___heap_base = 1048624u;
}

static wasm_rt_memory_t w2c_memory;

static void w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h0b8605991630ed23E(u32 w2c_p0) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21263, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = w2c_p0;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21264, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21260, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21261, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21254u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21254, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21252u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21252, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21248u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21248, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21252u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21252, w2c_i1);
  w2c_L0: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21252u);
    w2c_i1 = 1u;
    w2c_i0 &= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21248u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21248, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21252u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21252, w2c_i1);
  FUNC_EPILOGUE;
}

static void w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h9258f2dac55d64d2E(u32 w2c_p0) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 0u;
  w2c_i1 = w2c_p0;
  w2c_i2 = 8u;
  w2c_i1 >>= (w2c_i2 & 31);
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21090, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = w2c_p0;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21091, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21086, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21087, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21079u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21079, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21077u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21077, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21072u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21072, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21077u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21077, w2c_i1);
  w2c_L0: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21077u);
    w2c_i1 = 1u;
    w2c_i0 &= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21072u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21072, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21077u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21077, w2c_i1);
  FUNC_EPILOGUE;
}

static void w2c_app(void) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0, w2c_l4 = 0, w2c_l5 = 0, w2c_l6 = 0, w2c_l7 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3, w2c_i4;
  u64 w2c_j1;
  w2c_i0 = w2c___stack_pointer;
  w2c_i1 = 32u;
  w2c_i0 -= w2c_i1;
  w2c_l0 = w2c_i0;
  w2c___stack_pointer = w2c_i0;
  w2c_i0 = 0u;
  w2c_i1 = 1u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 1048616, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20678u);
  w2c_i2 = 231u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20678, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20678u);
  w2c_i2 = 248u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20678, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20487u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20487, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20488u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20488, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20489u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20489, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20482u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20482, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20483u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20483, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20484u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20484, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21088, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 15u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21089, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 4u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21262, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20497u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20497, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20498u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20498, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20499u);
  w2c_i2 = 32u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20499, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 2u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21043, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 104u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21042, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21045u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21045, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20495u);
  w2c_i2 = 251u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20495, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20497u);
  w2c_i2 = 4u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20497, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20498u);
  w2c_i2 = 4u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20498, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20499u);
  w2c_i2 = 4u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20499, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20495u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20495, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20497u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20497, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20498u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20498, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20499u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20499, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20497u);
  w2c_i2 = 191u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20497, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20498u);
  w2c_i2 = 191u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20498, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20499u);
  w2c_i2 = 191u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20499, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21505u);
  w2c_i2 = 143u;
  w2c_i1 &= w2c_i2;
  w2c_i2 = 64u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21505, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21506u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21506, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21505u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21505, w2c_i1);
  w2c_i0 = 1000000u;
  w2c_l1 = w2c_i0;
  w2c_L0: 
    w2c_i0 = 65535u;
    w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h9258f2dac55d64d2E(w2c_i0);
    w2c_i0 = w2c_l1;
    w2c_i1 = 4294901761u;
    w2c_i0 += w2c_i1;
    w2c_l1 = w2c_i0;
    w2c_i1 = 65535u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 16975u;
  w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h9258f2dac55d64d2E(w2c_i0);
  w2c_L2: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 20485u);
    w2c_l1 = w2c_i0;
    w2c_i0 = 0u;
    w2c_i1 = 0u;
    w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
    w2c_i2 = 223u;
    w2c_i1 &= w2c_i2;
    w2c_i2 = w2c_l1;
    w2c_i3 = 32u;
    w2c_i2 &= w2c_i3;
    w2c_i1 |= w2c_i2;
    w2c_i2 = 32u;
    w2c_i1 ^= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 0u;
    i32_store((&w2c_memory), (u64)(w2c_i0) + 16, w2c_i1);
    w2c_i0 = 12345678u;
    w2c_l2 = w2c_i0;
    w2c_i0 = 3u;
    w2c_l3 = w2c_i0;
    w2c_L4: 
      w2c_i0 = w2c_l3;
      w2c_i1 = 0u;
      w2c_i0 = (u32)((s32)w2c_i0 < (s32)w2c_i1);
      if (w2c_i0) {goto w2c_B1;}
      w2c_i0 = w2c_l0;
      w2c_i1 = 16u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l3;
      w2c_i0 += w2c_i1;
      w2c_l4 = w2c_i0;
      w2c_i0 = 0u;
      w2c_l5 = w2c_i0;
      w2c_i0 = 1u;
      w2c_l6 = w2c_i0;
      w2c_L5: 
        w2c_i0 = w2c_l2;
        w2c_l1 = w2c_i0;
        w2c_i1 = w2c_l1;
        w2c_i2 = 10u;
        w2c_i1 = I32_DIV_S(w2c_i1, w2c_i2);
        w2c_l2 = w2c_i1;
        w2c_i2 = 4294967286u;
        w2c_i1 *= w2c_i2;
        w2c_i0 += w2c_i1;
        w2c_l7 = w2c_i0;
        w2c_i1 = 256u;
        w2c_i0 = w2c_i0 >= w2c_i1;
        if (w2c_i0) {goto w2c_B3;}
        w2c_i0 = w2c_l4;
        w2c_i1 = w2c_l4;
        w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1));
        w2c_i2 = w2c_l7;
        w2c_i3 = w2c_l5;
        w2c_i4 = 255u;
        w2c_i3 &= w2c_i4;
        w2c_i2 <<= (w2c_i3 & 31);
        w2c_i1 |= w2c_i2;
        i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
        w2c_i0 = w2c_l6;
        w2c_i1 = 1u;
        w2c_i0 &= w2c_i1;
        w2c_l7 = w2c_i0;
        w2c_i0 = 4u;
        w2c_l5 = w2c_i0;
        w2c_i0 = 0u;
        w2c_l6 = w2c_i0;
        w2c_i0 = w2c_l7;
        if (w2c_i0) {goto w2c_L5;}
      w2c_i0 = w2c_l3;
      w2c_i1 = 4294967295u;
      w2c_i0 += w2c_i1;
      w2c_l3 = w2c_i0;
      w2c_i0 = w2c_l1;
      w2c_i1 = 9u;
      w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
      if (w2c_i0) {goto w2c_L4;}
    w2c_i0 = w2c_l0;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0) + 16u);
    w2c_l1 = w2c_i0;
    w2c_i0 = w2c_l0;
    w2c_j1 = 0ull;
    i64_store((&w2c_memory), (u64)(w2c_i0) + 16, w2c_j1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l1;
    i32_store((&w2c_memory), (u64)(w2c_i0) + 28, w2c_i1);
    w2c_i0 = 0u;
    w2c_l1 = w2c_i0;
    w2c_L6: 
      w2c_i0 = w2c_l0;
      w2c_i1 = 16u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l1;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l1;
      w2c_i2 = 48u;
      w2c_i1 |= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
      w2c_i0 = w2c_l1;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l1 = w2c_i0;
      w2c_i1 = 8u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L6;}
    w2c_i0 = 0u;
    w2c_l4 = w2c_i0;
    w2c_i0 = w2c_l0;
    w2c_i1 = 16u;
    w2c_i0 += w2c_i1;
    w2c_l1 = w2c_i0;
    w2c_L7: 
      w2c_i0 = w2c_l1;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l0;
      w2c_i2 = 28u;
      w2c_i1 += w2c_i2;
      w2c_i2 = w2c_l4;
      w2c_i1 += w2c_i2;
      w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1));
      w2c_l5 = w2c_i1;
      w2c_i2 = 15u;
      w2c_i1 &= w2c_i2;
      w2c_i2 = 48u;
      w2c_i1 |= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
      w2c_i0 = w2c_l1;
      w2c_i1 = w2c_l5;
      w2c_i2 = 4u;
      w2c_i1 >>= (w2c_i2 & 31);
      w2c_i2 = 48u;
      w2c_i1 |= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
      w2c_i0 = w2c_l1;
      w2c_i1 = 2u;
      w2c_i0 += w2c_i1;
      w2c_l1 = w2c_i0;
      w2c_i0 = w2c_l4;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l4 = w2c_i0;
      w2c_i1 = 4u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L7;}
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l0;
    w2c_j1 = i64_load((&w2c_memory), (u64)(w2c_i1) + 16u);
    i64_store((&w2c_memory), (u64)(w2c_i0) + 8, w2c_j1);
    w2c_i0 = 0u;
    w2c_l1 = w2c_i0;
    w2c_L8: 
      w2c_i0 = 0u;
      w2c_i1 = w2c_l0;
      w2c_i2 = 8u;
      w2c_i1 += w2c_i2;
      w2c_i2 = w2c_l1;
      w2c_i1 += w2c_i2;
      w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1));
      i32_store8((&w2c_memory), (u64)(w2c_i0) + 21041, w2c_i1);
      w2c_L9: 
        w2c_i0 = 0u;
        w2c_i0 = i32_load8_s((&w2c_memory), (u64)(w2c_i0) + 21040u);
        w2c_i1 = 4294967295u;
        w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
        if (w2c_i0) {goto w2c_L9;}
      w2c_i0 = w2c_l1;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l1 = w2c_i0;
      w2c_i1 = 8u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L8;}
    w2c_L10: 
      w2c_i0 = 0u;
      w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21040u);
      w2c_i1 = 64u;
      w2c_i0 &= w2c_i1;
      w2c_i0 = !(w2c_i0);
      if (w2c_i0) {goto w2c_L10;}
    w2c_i0 = 0u;
    w2c_l5 = w2c_i0;
    w2c_L11: 
      w2c_i0 = 0u;
      w2c_i1 = 0u;
      w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
      w2c_i2 = 247u;
      w2c_i1 &= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
      w2c_i0 = w2c_l0;
      w2c_i1 = 8u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l5;
      w2c_i0 += w2c_i1;
      w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0));
      w2c_l1 = w2c_i0;
      w2c_i0 = 96u;
      w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h0b8605991630ed23E(w2c_i0);
      w2c_i0 = 8u;
      w2c_l4 = w2c_i0;
      w2c_L12: 
        w2c_i0 = 0u;
        w2c_i1 = 0u;
        w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
        w2c_i2 = 247u;
        w2c_i1 &= w2c_i2;
        w2c_i2 = w2c_l1;
        w2c_i3 = 3u;
        w2c_i2 <<= (w2c_i3 & 31);
        w2c_i3 = 8u;
        w2c_i2 &= w2c_i3;
        w2c_i1 |= w2c_i2;
        i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
        w2c_i0 = 96u;
        w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h0b8605991630ed23E(w2c_i0);
        w2c_i0 = w2c_l1;
        w2c_i1 = 254u;
        w2c_i0 &= w2c_i1;
        w2c_i1 = 1u;
        w2c_i0 >>= (w2c_i1 & 31);
        w2c_l1 = w2c_i0;
        w2c_i0 = w2c_l4;
        w2c_i1 = 4294967295u;
        w2c_i0 += w2c_i1;
        w2c_l4 = w2c_i0;
        if (w2c_i0) {goto w2c_L12;}
      w2c_i0 = 0u;
      w2c_i1 = 0u;
      w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
      w2c_i2 = 8u;
      w2c_i1 |= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
      w2c_i0 = 96u;
      w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h0b8605991630ed23E(w2c_i0);
      w2c_i0 = w2c_l5;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l5 = w2c_i0;
      w2c_i1 = 8u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L11;}
    w2c_i0 = 2000000u;
    w2c_l1 = w2c_i0;
    w2c_L13: 
      w2c_i0 = 65535u;
      w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h9258f2dac55d64d2E(w2c_i0);
      w2c_i0 = w2c_l1;
      w2c_i1 = 4294901761u;
      w2c_i0 += w2c_i1;
      w2c_l1 = w2c_i0;
      w2c_i1 = 65535u;
      w2c_i0 = w2c_i0 > w2c_i1;
      if (w2c_i0) {goto w2c_L13;}
    w2c_i0 = 33950u;
    w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h9258f2dac55d64d2E(w2c_i0);
    goto w2c_L2;
    w2c_B3:;
  w2c_i0 = 1048576u;
  w2c_i1 = 40u;
  w2c__ZN4core9panicking5panic17h3b99507adb69386aE(w2c_i0, w2c_i1);
  UNREACHABLE;
  w2c_B1:;
  w2c_i0 = w2c_l0;
  w2c_i1 = 16u;
  w2c_i0 += w2c_i1;
  w2c__ZN4core6result13unwrap_failed17h4ed86702351a3017E(w2c_i0);
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static void w2c__ZN4core9panicking5panic17h3b99507adb69386aE(u32 w2c_p0, u32 w2c_p1) {
  FUNC_PROLOGUE;
  w2c__ZN4core9panicking9panic_fmt17h5c7ce52813e94bcdE();
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static void w2c__ZN4core6result13unwrap_failed17h4ed86702351a3017E(u32 w2c_p0) {
  FUNC_PROLOGUE;
  w2c__ZN4core9panicking9panic_fmt17h5c7ce52813e94bcdE();
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static void w2c__ZN4core9panicking9panic_fmt17h5c7ce52813e94bcdE(void) {
  FUNC_PROLOGUE;
  w2c_rust_begin_unwind();
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static void w2c_rust_begin_unwind(void) {
  FUNC_PROLOGUE;
  w2c_L0: 
    goto w2c_L0;
  FUNC_EPILOGUE;
}

static const u8 data_segment_data_0[] = {
  0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x20, 0x65, 0x72, 0x72, 
  0x6f, 0x72, 0x3a, 0x20, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x64, 0x20, 
  0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x20, 
  0x63, 0x6f, 0x64, 0x65, 
};

static void init_memory(void) {
  wasm_rt_allocate_memory((&w2c_memory), 17, 65536);
  LOAD_DATA(w2c_memory, 1048576u, data_segment_data_0, 40);
}

static void init_table(void) {
  uint32_t offset;
}

/* export: 'memory' */
wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: 'app' */
void (*WASM_RT_ADD_PREFIX(Z_appZ_vv))(void);
/* export: 'DEVICE_PERIPHERALS' */
u32 (*WASM_RT_ADD_PREFIX(Z_DEVICE_PERIPHERALSZ_i));
/* export: '__data_end' */
u32 (*WASM_RT_ADD_PREFIX(Z___data_endZ_i));
/* export: '__heap_base' */
u32 (*WASM_RT_ADD_PREFIX(Z___heap_baseZ_i));

static void init_exports(void) {
  /* export: 'memory' */
  WASM_RT_ADD_PREFIX(Z_memory) = (&w2c_memory);
  /* export: 'app' */
  WASM_RT_ADD_PREFIX(Z_appZ_vv) = (&w2c_app);
  /* export: 'DEVICE_PERIPHERALS' */
  WASM_RT_ADD_PREFIX(Z_DEVICE_PERIPHERALSZ_i) = (&w2c_DEVICE_PERIPHERALS);
  /* export: '__data_end' */
  WASM_RT_ADD_PREFIX(Z___data_endZ_i) = (&w2c___data_end);
  /* export: '__heap_base' */
  WASM_RT_ADD_PREFIX(Z___heap_baseZ_i) = (&w2c___heap_base);
}

void WASM_RT_ADD_PREFIX(init)(void) {
  init_func_types();
  init_globals();
  init_memory();
  init_table();
  init_exports();
}
