/* Automically generated by wasm2c */
#include <math.h>
#include <string.h>

#include "app_polluted.h"
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#define LIKELY(x) __builtin_expect(!!(x), 1)

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION)

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth

#define UNREACHABLE TRAP(UNREACHABLE)

#define CALL_INDIRECT(table, t, ft, x, ...)          \
  (LIKELY((x) < table.size && table.data[x].func &&  \
          table.data[x].func_type == func_types[ft]) \
       || TRAP(CALL_INDIRECT)                        \
       , ((t)table.data[x].func)(__VA_ARGS__))

#if WASM_RT_MEMCHECK_SIGNAL_HANDLER
#define MEMCHECK(mem, a, t)
#else
#define MEMCHECK(mem, a, t)  \
  if (UNLIKELY((a) + sizeof(t) > mem->size)) TRAP(OOB)
#endif

#if WABT_BIG_ENDIAN
static inline void load_data(void *dest, const void *src, size_t n) {
  size_t i = 0;
  u8 *dest_chars = dest;
  memcpy(dest, src, n);
  for (i = 0; i < (n>>1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[m.size - o - s]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                                                 \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {                            \
    MEMCHECK(mem, addr, t1);                                                          \
    t1 result;                                                                        \
    __builtin_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], sizeof(t1)); \
    return (t3)(t2)result;                                                            \
  }

#define DEFINE_STORE(name, t1, t2)                                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) {                 \
    MEMCHECK(mem, addr, t1);                                                           \
    t1 wrapped = (t1)value;                                                            \
    __builtin_memcpy(&mem->data[mem->size - addr - sizeof(t1)], &wrapped, sizeof(t1)); \
  }
#else
static inline void load_data(void *dest, const void *src, size_t n) {
  memcpy(dest, src, n);
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[o]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                        \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {   \
    MEMCHECK(mem, addr, t1);                                 \
    t1 result;                                               \
    __builtin_memcpy(&result, &mem->data[addr], sizeof(t1)); \
    return (t3)(t2)result;                                   \
  }

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) { \
    MEMCHECK(mem, addr, t1);                                           \
    t1 wrapped = (t1)value;                                            \
    __builtin_memcpy(&mem->data[addr], &wrapped, sizeof(t1));          \
  }
#endif

DEFINE_LOAD(i32_load, u32, u32, u32);
DEFINE_LOAD(i64_load, u64, u64, u64);
DEFINE_LOAD(f32_load, f32, f32, f32);
DEFINE_LOAD(f64_load, f64, f64, f64);
DEFINE_LOAD(i32_load8_s, s8, s32, u32);
DEFINE_LOAD(i64_load8_s, s8, s64, u64);
DEFINE_LOAD(i32_load8_u, u8, u32, u32);
DEFINE_LOAD(i64_load8_u, u8, u64, u64);
DEFINE_LOAD(i32_load16_s, s16, s32, u32);
DEFINE_LOAD(i64_load16_s, s16, s64, u64);
DEFINE_LOAD(i32_load16_u, u16, u32, u32);
DEFINE_LOAD(i64_load16_u, u16, u64, u64);
DEFINE_LOAD(i64_load32_s, s32, s64, u64);
DEFINE_LOAD(i64_load32_u, u32, u64, u64);
DEFINE_STORE(i32_store, u32, u32);
DEFINE_STORE(i64_store, u64, u64);
DEFINE_STORE(f32_store, f32, f32);
DEFINE_STORE(f64_store, f64, f64);
DEFINE_STORE(i32_store8, u8, u32);
DEFINE_STORE(i32_store16, u16, u32);
DEFINE_STORE(i64_store8, u8, u64);
DEFINE_STORE(i64_store16, u16, u64);
DEFINE_STORE(i64_store32, u32, u64);

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#define DIV_S(ut, min, x, y)                                 \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO)  \
  : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
  : (ut)((x) / (y)))

#define REM_S(ut, min, x, y)                                \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO) \
  : (UNLIKELY((x) == min && (y) == -1)) ? 0                 \
  : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x) op (y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
  : (x < y) ? x : y)

#define FMAX(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
  : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                             \
  ((UNLIKELY((x) != (x)))                        ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                 : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                            \
  ((UNLIKELY((x) != (x)))                       ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296.,  x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))         ? 0                           \
   : (UNLIKELY(!((x)minop(min)))) ? smin                        \
   : (UNLIKELY(!((x) < (max))))   ? smax                        \
                                  : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F32(x) TRUNC_SAT_S(u32, s32, f32, (f32)INT32_MIN, INT32_MIN, >=, 2147483648.f, INT32_MAX, x)
#define I64_TRUNC_SAT_S_F32(x) TRUNC_SAT_S(u64, s64, f32, (f32)INT64_MIN, INT64_MIN, >=, (f32)INT64_MAX, INT64_MAX, x)
#define I32_TRUNC_SAT_S_F64(x) TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., INT32_MAX, x)
#define I64_TRUNC_SAT_S_F64(x) TRUNC_SAT_S(u64, s64, f64, (f64)INT64_MIN, INT64_MIN, >=, (f64)INT64_MAX, INT64_MAX, x)

#define TRUNC_SAT_U(ut, ft, max, smax, x) \
  ((UNLIKELY((x) != (x)))        ? 0      \
   : (UNLIKELY(!((x) > (ft)-1))) ? 0      \
   : (UNLIKELY(!((x) < (max))))  ? smax   \
                                 : (ut)(x))

#define I32_TRUNC_SAT_U_F32(x) TRUNC_SAT_U(u32, f32, 4294967296.f, UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F32(x) TRUNC_SAT_U(u64, f32, (f32)UINT64_MAX, UINT64_MAX, x)
#define I32_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u32, f64, 4294967296., UINT32_MAX,  x)
#define I64_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u64, f64, (f64)UINT64_MAX, UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)  \
  static inline t2 name(t1 x) {           \
    t2 result;                            \
    memcpy(&result, &x, sizeof(result));  \
    return result;                        \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)


static u32 func_types[3];

static void init_func_types(void) {
  func_types[0] = wasm_rt_register_func_type(1, 0, WASM_RT_I32);
  func_types[1] = wasm_rt_register_func_type(1, 1, WASM_RT_I32, WASM_RT_I32);
  func_types[2] = wasm_rt_register_func_type(0, 0);
}

static void w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h900273c7f7bdb844E(u32);
static void w2c__ZN83__LT_stm8s_hal__timer__Timer_LT_TIM_GT__u20_as_u20_embedded_hal__delay__DelayNs_GT_8delay_ns17h04eb114913a92cf5E(u32);
static void w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(u32);
static void w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(u32);
static u32 w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_12send_command17he12d3fe51fc08a43E(u32);
static void w2c_app(void);
static u32 w2c__ZN9stm8s_hal3adc26Adc_LT_stm8s_pac__ADC1_GT_4read17hda6c234840b1e9e2E(u32);
static void w2c__ZN4core6result13unwrap_failed17h4ec8ebc0cd29f54bE(u32);
static void w2c__ZN4core9panicking9panic_fmt17h619600efce2da276E(void);
static void w2c_rust_begin_unwind(void);

static u32 w2c___stack_pointer;
static u32 w2c_DEVICE_PERIPHERALS;
static u32 w2c___data_end;
static u32 w2c___heap_base;

static void init_globals(void) {
  w2c___stack_pointer = 1048576u;
  w2c_DEVICE_PERIPHERALS = 1048844u;
  w2c___data_end = 1048845u;
  w2c___heap_base = 1048848u;
}

static wasm_rt_memory_t w2c_memory;

static void w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h900273c7f7bdb844E(u32 w2c_p0) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21263, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = w2c_p0;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21264, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21260, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21261, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21254u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21254, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21252u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21252, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21248u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21248, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21252u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21252, w2c_i1);
  w2c_L0: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21252u);
    w2c_i1 = 1u;
    w2c_i0 &= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21248u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21248, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21252u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21252, w2c_i1);
  FUNC_EPILOGUE;
}

static void w2c__ZN83__LT_stm8s_hal__timer__Timer_LT_TIM_GT__u20_as_u20_embedded_hal__delay__DelayNs_GT_8delay_ns17h04eb114913a92cf5E(u32 w2c_p0) {
  u32 w2c_l1 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1;
  w2c_i0 = w2c_p0;
  w2c_i1 = 1000u;
  w2c_i0 = DIV_U(w2c_i0, w2c_i1);
  w2c_l1 = w2c_i0;
  w2c_i0 = w2c_p0;
  w2c_i1 = 65536000u;
  w2c_i0 = w2c_i0 < w2c_i1;
  if (w2c_i0) {goto w2c_B0;}
  w2c_L1: 
    w2c_i0 = 65535u;
    w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
    w2c_i0 = w2c_l1;
    w2c_i1 = 4294901761u;
    w2c_i0 += w2c_i1;
    w2c_l1 = w2c_i0;
    w2c_i1 = 65535u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) {goto w2c_L1;}
  w2c_B0:;
  w2c_i0 = w2c_l1;
  w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
  FUNC_EPILOGUE;
}

static void w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(u32 w2c_p0) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 0u;
  w2c_i1 = w2c_p0;
  w2c_i2 = 8u;
  w2c_i1 >>= (w2c_i2 & 31);
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21090, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = w2c_p0;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21091, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21086, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21087, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21079u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21079, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21077u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21077, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21072u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21072, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21077u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21077, w2c_i1);
  w2c_L0: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21077u);
    w2c_i1 = 1u;
    w2c_i0 &= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21072u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21072, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21077u);
  w2c_i2 = 254u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21077, w2c_i1);
  FUNC_EPILOGUE;
}

static void w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(u32 w2c_p0) {
  u32 w2c_l1 = 0, w2c_l2 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3;
  w2c_i0 = 8u;
  w2c_l1 = w2c_i0;
  w2c_L0: 
    w2c_i0 = 0u;
    w2c_i1 = 0u;
    w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
    w2c_i2 = 239u;
    w2c_i1 &= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
    w2c_i0 = 1u;
    w2c_i1 = 52u;
    w2c_i2 = w2c_p0;
    w2c_i3 = 1u;
    w2c_i2 &= w2c_i3;
    w2c_l2 = w2c_i2;
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
    w2c_i0 = 0u;
    w2c_i1 = 0u;
    w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
    w2c_i2 = 16u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
    w2c_i0 = 56000u;
    w2c_i1 = 2000u;
    w2c_i2 = w2c_l2;
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c__ZN83__LT_stm8s_hal__timer__Timer_LT_TIM_GT__u20_as_u20_embedded_hal__delay__DelayNs_GT_8delay_ns17h04eb114913a92cf5E(w2c_i0);
    w2c_i0 = w2c_p0;
    w2c_i1 = 254u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 1u;
    w2c_i0 >>= (w2c_i1 & 31);
    w2c_p0 = w2c_i0;
    w2c_i0 = w2c_l1;
    w2c_i1 = 4294967295u;
    w2c_i0 += w2c_i1;
    w2c_l1 = w2c_i0;
    if (w2c_i0) {goto w2c_L0;}
  FUNC_EPILOGUE;
}

static u32 w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_12send_command17he12d3fe51fc08a43E(u32 w2c_p0) {
  u32 w2c_l1 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 125u;
  w2c_l1 = w2c_i0;
  w2c_L1: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 20486u);
    w2c_i1 = 16u;
    w2c_i0 &= w2c_i1;
    if (w2c_i0) {goto w2c_B0;}
    w2c_i0 = 2u;
    w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
    w2c_i0 = w2c_l1;
    w2c_i1 = 4294967295u;
    w2c_i0 += w2c_i1;
    w2c_l1 = w2c_i0;
    if (w2c_i0) {goto w2c_L1;}
  w2c_i0 = 0u;
  goto w2c_Bfunc;
  w2c_B0:;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
  w2c_i2 = 239u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
  w2c_i0 = 480u;
  w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
  w2c_i2 = 16u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
  w2c_i0 = 70u;
  w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
  w2c_i0 = 0u;
  w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 20486u);
  w2c_l1 = w2c_i0;
  w2c_i0 = 410u;
  w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
  w2c_i0 = 204u;
  w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(w2c_i0);
  w2c_i0 = w2c_p0;
  w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(w2c_i0);
  w2c_i0 = 6u;
  w2c_Bfunc:;
  FUNC_EPILOGUE;
  return w2c_i0;
}

static void w2c_app(void) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0, w2c_l4 = 0, w2c_l5 = 0, w2c_l6 = 0, w2c_l7 = 0, 
      w2c_l8 = 0, w2c_l9 = 0, w2c_l10 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3;
  u64 w2c_j1;
  w2c_i0 = w2c___stack_pointer;
  w2c_i1 = 48u;
  w2c_i0 -= w2c_i1;
  w2c_l0 = w2c_i0;
  w2c___stack_pointer = w2c_i0;
  w2c_i0 = 0u;
  w2c_i1 = 1u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 1048844, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20678u);
  w2c_i2 = 231u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20678, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20678u);
  w2c_i2 = 248u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20678, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21088, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 15u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21089, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 4u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21262, w2c_i1);
  w2c_i0 = 500000000u;
  w2c__ZN83__LT_stm8s_hal__timer__Timer_LT_TIM_GT__u20_as_u20_embedded_hal__delay__DelayNs_GT_8delay_ns17h04eb114913a92cf5E(w2c_i0);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20492u);
  w2c_i2 = 239u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20492, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20493u);
  w2c_i2 = 239u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20493, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20494u);
  w2c_i2 = 239u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20494, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20497u);
  w2c_i2 = 191u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20497, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20498u);
  w2c_i2 = 191u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20498, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20499u);
  w2c_i2 = 191u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20499, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21505u);
  w2c_i2 = 143u;
  w2c_i1 &= w2c_i2;
  w2c_i2 = 64u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21505, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21506u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21506, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21505u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21505, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20487u);
  w2c_i2 = 16u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20487, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20488u);
  w2c_i2 = 239u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20488, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20489u);
  w2c_i2 = 16u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20489, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
  w2c_i2 = 16u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
  w2c_i0 = 78u;
  w2c_i0 = w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_12send_command17he12d3fe51fc08a43E(w2c_i0);
  w2c_i1 = 255u;
  w2c_i0 &= w2c_i1;
  w2c_i1 = 6u;
  w2c_i0 = w2c_i0 != w2c_i1;
  if (w2c_i0) {goto w2c_B0;}
  w2c_i0 = 127u;
  w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(w2c_i0);
  w2c_i0 = 128u;
  w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(w2c_i0);
  w2c_i0 = 31u;
  w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_10write_byte17h81f40adecc57c4c2E(w2c_i0);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20482u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20482, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20483u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20483, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20484u);
  w2c_i2 = 8u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20484, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
  w2c_i2 = 247u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 204u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20704, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 85u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20704, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 4u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20705, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 250u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20706, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 170u;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 20704, w2c_i1);
  w2c_i0 = w2c_l0;
  w2c_i1 = 41u;
  w2c_i0 += w2c_i1;
  w2c_l1 = w2c_i0;
  w2c_i0 = 2147483647u;
  w2c_l2 = w2c_i0;
  w2c_i0 = 2147483648u;
  w2c_l3 = w2c_i0;
  w2c_i0 = 2147483648u;
  w2c_l4 = w2c_i0;
  w2c_i0 = 0u;
  w2c_l5 = w2c_i0;
  w2c_i0 = 0u;
  w2c_l6 = w2c_i0;
  w2c_i0 = 0u;
  w2c_l7 = w2c_i0;
  w2c_L1: 
    w2c_i0 = 2u;
    w2c_i0 = w2c__ZN9stm8s_hal3adc26Adc_LT_stm8s_pac__ADC1_GT_4read17hda6c234840b1e9e2E(w2c_i0);
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 680u;
    w2c_i0 *= w2c_i1;
    w2c_i1 = 1000u;
    w2c_i0 = DIV_U(w2c_i0, w2c_i1);
    w2c_i1 = w2c_l5;
    w2c_i2 = 320u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = 1000u;
    w2c_i1 = I32_DIV_S(w2c_i1, w2c_i2);
    w2c_i0 += w2c_i1;
    w2c_l5 = w2c_i0;
    w2c_i1 = w2c_l3;
    w2c_i2 = w2c_l5;
    w2c_i3 = w2c_l3;
    w2c_i2 = (u32)((s32)w2c_i2 > (s32)w2c_i3);
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_l3 = w2c_i0;
    w2c_i0 = 6u;
    w2c_i0 = w2c__ZN9stm8s_hal3adc26Adc_LT_stm8s_pac__ADC1_GT_4read17hda6c234840b1e9e2E(w2c_i0);
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 680u;
    w2c_i0 *= w2c_i1;
    w2c_i1 = 1000u;
    w2c_i0 = DIV_U(w2c_i0, w2c_i1);
    w2c_i1 = w2c_l6;
    w2c_i2 = 320u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = 1000u;
    w2c_i1 = I32_DIV_S(w2c_i1, w2c_i2);
    w2c_i0 += w2c_i1;
    w2c_l6 = w2c_i0;
    w2c_i1 = w2c_l2;
    w2c_i2 = w2c_l6;
    w2c_i3 = w2c_l2;
    w2c_i2 = (u32)((s32)w2c_i2 < (s32)w2c_i3);
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_i0 = w2c_l6;
    w2c_i1 = w2c_l4;
    w2c_i2 = w2c_l6;
    w2c_i3 = w2c_l4;
    w2c_i2 = (u32)((s32)w2c_i2 > (s32)w2c_i3);
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_l4 = w2c_i0;
    w2c_i0 = w2c_l7;
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_l8 = w2c_i0;
    w2c_i0 = w2c_l7;
    w2c_i1 = 1u;
    w2c_i0 += w2c_i1;
    w2c_l7 = w2c_i0;
    w2c_i0 = w2c_l8;
    w2c_i1 = 165u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) {goto w2c_L1;}
    w2c_i0 = w2c_l4;
    w2c_i1 = w2c_l2;
    w2c_i0 -= w2c_i1;
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 3300u;
    w2c_i0 *= w2c_i1;
    w2c_i1 = 16368u;
    w2c_i0 = DIV_U(w2c_i0, w2c_i1);
    w2c_l9 = w2c_i0;
    w2c_i0 = w2c_l3;
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 3300u;
    w2c_i0 *= w2c_i1;
    w2c_i1 = 1023u;
    w2c_i0 = DIV_U(w2c_i0, w2c_i1);
    w2c_i1 = 3633u;
    w2c_i0 *= w2c_i1;
    w2c_i1 = 33000u;
    w2c_i0 = DIV_U(w2c_i0, w2c_i1);
    w2c_l10 = w2c_i0;
    w2c_i0 = 68u;
    w2c_i0 = w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_12send_command17he12d3fe51fc08a43E(w2c_i0);
    w2c_i1 = 255u;
    w2c_i0 &= w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_i1 = 6u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) {goto w2c_B4;}
    w2c_i0 = 94000000u;
    w2c__ZN83__LT_stm8s_hal__timer__Timer_LT_TIM_GT__u20_as_u20_embedded_hal__delay__DelayNs_GT_8delay_ns17h04eb114913a92cf5E(w2c_i0);
    w2c_i0 = 190u;
    w2c_i0 = w2c__ZN9stm8s_hal8one_wire18OneWire_LT_Pin_GT_12send_command17he12d3fe51fc08a43E(w2c_i0);
    w2c_i1 = 255u;
    w2c_i0 &= w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_i1 = 6u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) {goto w2c_B6;}
    w2c_i0 = 0u;
    w2c_l7 = w2c_i0;
    w2c_i0 = w2c_l0;
    w2c_i1 = 24u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 8u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 0u;
    i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_j1 = 0ull;
    i64_store((&w2c_memory), (u64)(w2c_i0) + 24, w2c_j1);
    w2c_L7: 
      w2c_i0 = 8u;
      w2c_l3 = w2c_i0;
      w2c_i0 = 0u;
      w2c_l2 = w2c_i0;
      w2c_L8: 
        w2c_i0 = 0u;
        w2c_i1 = 0u;
        w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
        w2c_i2 = 239u;
        w2c_i1 &= w2c_i2;
        i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
        w2c_i0 = 1u;
        w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
        w2c_i0 = 0u;
        w2c_i1 = 0u;
        w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20485u);
        w2c_i2 = 16u;
        w2c_i1 |= w2c_i2;
        i32_store8((&w2c_memory), (u64)(w2c_i0) + 20485, w2c_i1);
        w2c_i0 = 1u;
        w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
        w2c_i0 = 0u;
        w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 20486u);
        w2c_l4 = w2c_i0;
        w2c_i0 = 47u;
        w2c__ZN9stm8s_hal5timer9TimerBase17internal_delay_us17h3192457b653ed6f6E(w2c_i0);
        w2c_i0 = w2c_l4;
        w2c_i1 = 3u;
        w2c_i0 <<= (w2c_i1 & 31);
        w2c_i1 = 4294967168u;
        w2c_i0 &= w2c_i1;
        w2c_i1 = w2c_l2;
        w2c_i2 = 254u;
        w2c_i1 &= w2c_i2;
        w2c_i2 = 1u;
        w2c_i1 >>= (w2c_i2 & 31);
        w2c_i0 |= w2c_i1;
        w2c_l2 = w2c_i0;
        w2c_i0 = w2c_l3;
        w2c_i1 = 4294967295u;
        w2c_i0 += w2c_i1;
        w2c_l3 = w2c_i0;
        if (w2c_i0) {goto w2c_L8;}
      w2c_i0 = w2c_l0;
      w2c_i1 = 24u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l7;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l2;
      i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
      w2c_i0 = w2c_l7;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l7 = w2c_i0;
      w2c_i1 = 9u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L7;}
    w2c_i0 = 0u;
    w2c_l3 = w2c_i0;
    w2c_i0 = 0u;
    w2c_l8 = w2c_i0;
    goto w2c_B5;
    w2c_B6:;
    w2c_i0 = w2c_l2;
    w2c_i1 = 8u;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_l2 = w2c_i0;
    goto w2c_B3;
    w2c_B5:;
    w2c_L9: 
      w2c_i0 = w2c_l0;
      w2c_i1 = 24u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l8;
      w2c_i0 += w2c_i1;
      w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0));
      w2c_l2 = w2c_i0;
      w2c_i0 = 8u;
      w2c_l4 = w2c_i0;
      w2c_L10: 
        w2c_i0 = w2c_l3;
        w2c_i1 = 1u;
        w2c_i0 >>= (w2c_i1 & 31);
        w2c_i1 = 127u;
        w2c_i0 &= w2c_i1;
        w2c_l7 = w2c_i0;
        w2c_i1 = 4294967180u;
        w2c_i0 ^= w2c_i1;
        w2c_i1 = w2c_l7;
        w2c_i2 = w2c_l2;
        w2c_i3 = w2c_l3;
        w2c_i2 ^= w2c_i3;
        w2c_i3 = 1u;
        w2c_i2 &= w2c_i3;
        w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
        w2c_l3 = w2c_i0;
        w2c_i0 = w2c_l2;
        w2c_i1 = 254u;
        w2c_i0 &= w2c_i1;
        w2c_i1 = 1u;
        w2c_i0 >>= (w2c_i1 & 31);
        w2c_l2 = w2c_i0;
        w2c_i0 = w2c_l4;
        w2c_i1 = 4294967295u;
        w2c_i0 += w2c_i1;
        w2c_l4 = w2c_i0;
        if (w2c_i0) {goto w2c_L10;}
      w2c_i0 = w2c_l8;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l8 = w2c_i0;
      w2c_i1 = 9u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L9;}
    w2c_i0 = w2c_l3;
    if (w2c_i0) {goto w2c_B11;}
    w2c_i0 = w2c_l0;
    w2c_i0 = i32_load16_s((&w2c_memory), (u64)(w2c_i0) + 24u);
    w2c_i1 = 16u;
    w2c_i0 = I32_DIV_S(w2c_i0, w2c_i1);
    w2c_i1 = 16u;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_l2 = w2c_i0;
    w2c_i0 = 1u;
    w2c_l3 = w2c_i0;
    goto w2c_B2;
    w2c_B11:;
    w2c_i0 = 1024u;
    w2c_l2 = w2c_i0;
    goto w2c_B3;
    w2c_B4:;
    w2c_i0 = w2c_l2;
    w2c_i1 = 8u;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_l2 = w2c_i0;
    w2c_B3:;
    w2c_i0 = 0u;
    w2c_l3 = w2c_i0;
    w2c_B2:;
    w2c_i0 = w2c_l1;
    w2c_i1 = 4u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 0u;
    i32_store8((&w2c_memory), (u64)(w2c_i0), w2c_i1);
    w2c_i0 = w2c_l1;
    w2c_i1 = 0u;
    i32_store((&w2c_memory), (u64)(w2c_i0), w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 978591809u;
    i32_store((&w2c_memory), (u64)(w2c_i0) + 37, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 46u;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 35, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 977870934u;
    i32_store((&w2c_memory), (u64)(w2c_i0) + 29, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 14933u;
    i32_store16((&w2c_memory), (u64)(w2c_i0) + 24, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 67u;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 44, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l9;
    w2c_i2 = 100u;
    w2c_i1 = DIV_U(w2c_i1, w2c_i2);
    w2c_l4 = w2c_i1;
    w2c_i2 = 48u;
    w2c_i1 += w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 33, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l10;
    w2c_i2 = 100u;
    w2c_i1 = DIV_U(w2c_i1, w2c_i2);
    w2c_l7 = w2c_i1;
    w2c_i2 = 48u;
    w2c_i1 += w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 26, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l4;
    w2c_i2 = 156u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = w2c_l9;
    w2c_i1 += w2c_i2;
    w2c_l4 = w2c_i1;
    w2c_i2 = 255u;
    w2c_i1 &= w2c_i2;
    w2c_i2 = 10u;
    w2c_i1 = DIV_U(w2c_i1, w2c_i2);
    w2c_l8 = w2c_i1;
    w2c_i2 = 48u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 34, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l7;
    w2c_i2 = 156u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = w2c_l10;
    w2c_i1 += w2c_i2;
    w2c_l7 = w2c_i1;
    w2c_i2 = 255u;
    w2c_i1 &= w2c_i2;
    w2c_i2 = 10u;
    w2c_i1 = DIV_U(w2c_i1, w2c_i2);
    w2c_l9 = w2c_i1;
    w2c_i2 = 48u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 27, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l8;
    w2c_i2 = 4294967286u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = w2c_l4;
    w2c_i1 += w2c_i2;
    w2c_i2 = 48u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 36, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l9;
    w2c_i2 = 4294967286u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = w2c_l7;
    w2c_i1 += w2c_i2;
    w2c_i2 = 48u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 28, w2c_i1);
    w2c_i0 = w2c_l3;
    if (w2c_i0) {goto w2c_B13;}
    w2c_i0 = w2c_l0;
    w2c_i1 = 542265925u;
    i32_store((&w2c_memory), (u64)(w2c_i0) + 41, w2c_i1);
    goto w2c_B12;
    w2c_B13:;
    w2c_i0 = w2c_l2;
    w2c_i1 = 16u;
    w2c_i0 >>= (w2c_i1 & 31);
    w2c_l3 = w2c_i0;
    w2c_i0 = w2c_l2;
    w2c_i1 = 4294967295u;
    w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
    if (w2c_i0) {goto w2c_B15;}
    w2c_i0 = 0u;
    w2c_i1 = w2c_l3;
    w2c_i0 -= w2c_i1;
    w2c_i1 = 65535u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 100u;
    w2c_i0 = REM_U(w2c_i0, w2c_i1);
    w2c_l2 = w2c_i0;
    w2c_i0 = 45u;
    w2c_l4 = w2c_i0;
    goto w2c_B14;
    w2c_B15:;
    w2c_i0 = w2c_l3;
    w2c_i1 = 100u;
    w2c_i0 = DIV_U(w2c_i0, w2c_i1);
    w2c_l2 = w2c_i0;
    w2c_i1 = 48u;
    w2c_i0 += w2c_i1;
    w2c_l4 = w2c_i0;
    w2c_i0 = w2c_l2;
    w2c_i1 = 156u;
    w2c_i0 *= w2c_i1;
    w2c_i1 = w2c_l3;
    w2c_i0 += w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_B14:;
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l4;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 41, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l2;
    w2c_i2 = 255u;
    w2c_i1 &= w2c_i2;
    w2c_i2 = 10u;
    w2c_i1 = DIV_U(w2c_i1, w2c_i2);
    w2c_l3 = w2c_i1;
    w2c_i2 = 48u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 42, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l3;
    w2c_i2 = 4294967286u;
    w2c_i1 *= w2c_i2;
    w2c_i2 = w2c_l2;
    w2c_i1 += w2c_i2;
    w2c_i2 = 48u;
    w2c_i1 |= w2c_i2;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 43, w2c_i1);
    w2c_B12:;
    w2c_i0 = 0u;
    w2c_l3 = w2c_i0;
    w2c_i0 = 0u;
    w2c_l2 = w2c_i0;
    w2c_L16: 
      w2c_i0 = w2c_l0;
      w2c_i1 = 24u;
      w2c_i0 += w2c_i1;
      w2c_i1 = w2c_l2;
      w2c_i0 += w2c_i1;
      w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = w2c_l3;
      w2c_i2 = 255u;
      w2c_i1 &= w2c_i2;
      w2c_i0 ^= w2c_i1;
      w2c_i1 = 1048588u;
      w2c_i0 += w2c_i1;
      w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0));
      w2c_l3 = w2c_i0;
      w2c_i0 = w2c_l2;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l4 = w2c_i0;
      w2c_l2 = w2c_i0;
      w2c_i0 = w2c_l4;
      w2c_i1 = 21u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L16;}
    w2c_i0 = w2c_l0;
    w2c_i1 = 8u;
    w2c_i0 += w2c_i1;
    w2c_i1 = w2c_l0;
    w2c_i2 = 24u;
    w2c_i1 += w2c_i2;
    w2c_i2 = 8u;
    w2c_i1 += w2c_i2;
    w2c_j1 = i64_load((&w2c_memory), (u64)(w2c_i1));
    i64_store((&w2c_memory), (u64)(w2c_i0), w2c_j1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l3;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 45, w2c_i1);
    w2c_i0 = w2c_l0;
    w2c_i1 = 14u;
    w2c_i0 += w2c_i1;
    w2c_i1 = w2c_l0;
    w2c_i2 = 24u;
    w2c_i1 += w2c_i2;
    w2c_i2 = 14u;
    w2c_i1 += w2c_i2;
    w2c_j1 = i64_load((&w2c_memory), (u64)(w2c_i1));
    i64_store((&w2c_memory), (u64)(w2c_i0), w2c_j1);
    w2c_i0 = w2c_l0;
    w2c_i1 = w2c_l0;
    w2c_j1 = i64_load((&w2c_memory), (u64)(w2c_i1) + 24u);
    i64_store((&w2c_memory), (u64)(w2c_i0), w2c_j1);
    w2c_i0 = 0u;
    w2c_l4 = w2c_i0;
    w2c_L17: 
      w2c_i0 = 8u;
      w2c_l3 = w2c_i0;
      w2c_i0 = 0u;
      w2c_i1 = 0u;
      w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
      w2c_i2 = 8u;
      w2c_i1 |= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
      w2c_i0 = w2c_l0;
      w2c_i1 = w2c_l4;
      w2c_i0 += w2c_i1;
      w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0));
      w2c_l2 = w2c_i0;
      w2c_i0 = 96u;
      w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h900273c7f7bdb844E(w2c_i0);
      w2c_L18: 
        w2c_i0 = 0u;
        w2c_i1 = 0u;
        w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
        w2c_i2 = 247u;
        w2c_i1 &= w2c_i2;
        w2c_i2 = w2c_l2;
        w2c_i3 = 3u;
        w2c_i2 <<= (w2c_i3 & 31);
        w2c_i3 = 8u;
        w2c_i2 &= w2c_i3;
        w2c_i1 |= w2c_i2;
        w2c_i2 = 8u;
        w2c_i1 ^= w2c_i2;
        i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
        w2c_i0 = 96u;
        w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h900273c7f7bdb844E(w2c_i0);
        w2c_i0 = w2c_l2;
        w2c_i1 = 254u;
        w2c_i0 &= w2c_i1;
        w2c_i1 = 1u;
        w2c_i0 >>= (w2c_i1 & 31);
        w2c_l2 = w2c_i0;
        w2c_i0 = w2c_l3;
        w2c_i1 = 4294967295u;
        w2c_i0 += w2c_i1;
        w2c_l3 = w2c_i0;
        if (w2c_i0) {goto w2c_L18;}
      w2c_i0 = 0u;
      w2c_i1 = 0u;
      w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 20480u);
      w2c_i2 = 247u;
      w2c_i1 &= w2c_i2;
      i32_store8((&w2c_memory), (u64)(w2c_i0) + 20480, w2c_i1);
      w2c_i0 = 96u;
      w2c__ZN12embedded_hal5delay7DelayNs8delay_us17h900273c7f7bdb844E(w2c_i0);
      w2c_i0 = w2c_l4;
      w2c_i1 = 1u;
      w2c_i0 += w2c_i1;
      w2c_l4 = w2c_i0;
      w2c_i1 = 22u;
      w2c_i0 = w2c_i0 != w2c_i1;
      if (w2c_i0) {goto w2c_L17;}
    w2c_i0 = 0u;
    w2c_l7 = w2c_i0;
    w2c_i0 = 0u;
    w2c_i1 = 170u;
    i32_store8((&w2c_memory), (u64)(w2c_i0) + 20704, w2c_i1);
    w2c_i0 = 2147483648u;
    w2c_l3 = w2c_i0;
    w2c_i0 = 2147483647u;
    w2c_l2 = w2c_i0;
    w2c_i0 = 2147483648u;
    w2c_l4 = w2c_i0;
    goto w2c_L1;
  w2c_B0:;
  w2c_i0 = w2c_l0;
  w2c_i1 = 24u;
  w2c_i0 += w2c_i1;
  w2c__ZN4core6result13unwrap_failed17h4ec8ebc0cd29f54bE(w2c_i0);
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static u32 w2c__ZN9stm8s_hal3adc26Adc_LT_stm8s_pac__ADC1_GT_4read17hda6c234840b1e9e2E(u32 w2c_p0) {
  u32 w2c_l1 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21504u);
  w2c_i2 = 240u;
  w2c_i1 &= w2c_i2;
  w2c_i2 = w2c_p0;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21504, w2c_i1);
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21505u);
  w2c_i2 = 1u;
  w2c_i1 |= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21505, w2c_i1);
  w2c_L0: 
    w2c_i0 = 0u;
    w2c_i0 = i32_load8_s((&w2c_memory), (u64)(w2c_i0) + 21504u);
    w2c_i1 = 4294967295u;
    w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
    if (w2c_i0) {goto w2c_L0;}
  w2c_i0 = 0u;
  w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21509u);
  w2c_p0 = w2c_i0;
  w2c_i0 = 0u;
  w2c_i0 = i32_load8_u((&w2c_memory), (u64)(w2c_i0) + 21508u);
  w2c_l1 = w2c_i0;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i1 = i32_load8_u((&w2c_memory), (u64)(w2c_i1) + 21504u);
  w2c_i2 = 127u;
  w2c_i1 &= w2c_i2;
  i32_store8((&w2c_memory), (u64)(w2c_i0) + 21504, w2c_i1);
  w2c_i0 = w2c_p0;
  w2c_i1 = w2c_l1;
  w2c_i2 = 8u;
  w2c_i1 <<= (w2c_i2 & 31);
  w2c_i0 |= w2c_i1;
  FUNC_EPILOGUE;
  return w2c_i0;
}

static void w2c__ZN4core6result13unwrap_failed17h4ec8ebc0cd29f54bE(u32 w2c_p0) {
  FUNC_PROLOGUE;
  w2c__ZN4core9panicking9panic_fmt17h619600efce2da276E();
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static void w2c__ZN4core9panicking9panic_fmt17h619600efce2da276E(void) {
  FUNC_PROLOGUE;
  w2c_rust_begin_unwind();
  UNREACHABLE;
  FUNC_EPILOGUE;
}

static void w2c_rust_begin_unwind(void) {
  FUNC_PROLOGUE;
  w2c_L0: 
    goto w2c_L0;
  FUNC_EPILOGUE;
}

static const u8 data_segment_data_0[] = {
  0x01, 0x01, 0x08, 0x1d, 0x00, 0x00, 0xf4, 0x00, 0x00, 0x00, 0x10, 0x00, 
  0x00, 0x64, 0xc8, 0xac, 0xe1, 0x85, 0x29, 0x4d, 0xb3, 0xd7, 0x7b, 0x1f, 
  0x52, 0x36, 0x9a, 0xfe, 0x17, 0x73, 0xdf, 0xbb, 0xf6, 0x92, 0x3e, 0x5a, 
  0xa4, 0xc0, 0x6c, 0x08, 0x45, 0x21, 0x8d, 0xe9, 0x2e, 0x4a, 0xe6, 0x82, 
  0xcf, 0xab, 0x07, 0x63, 0x9d, 0xf9, 0x55, 0x31, 0x7c, 0x18, 0xb4, 0xd0, 
  0x39, 0x5d, 0xf1, 0x95, 0xd8, 0xbc, 0x10, 0x74, 0x8a, 0xee, 0x42, 0x26, 
  0x6b, 0x0f, 0xa3, 0xc7, 0x5c, 0x38, 0x94, 0xf0, 0xbd, 0xd9, 0x75, 0x11, 
  0xef, 0x8b, 0x27, 0x43, 0x0e, 0x6a, 0xc6, 0xa2, 0x4b, 0x2f, 0x83, 0xe7, 
  0xaa, 0xce, 0x62, 0x06, 0xf8, 0x9c, 0x30, 0x54, 0x19, 0x7d, 0xd1, 0xb5, 
  0x72, 0x16, 0xba, 0xde, 0x93, 0xf7, 0x5b, 0x3f, 0xc1, 0xa5, 0x09, 0x6d, 
  0x20, 0x44, 0xe8, 0x8c, 0x65, 0x01, 0xad, 0xc9, 0x84, 0xe0, 0x4c, 0x28, 
  0xd6, 0xb2, 0x1e, 0x7a, 0x37, 0x53, 0xff, 0x9b, 0xb8, 0xdc, 0x70, 0x14, 
  0x59, 0x3d, 0x91, 0xf5, 0x0b, 0x6f, 0xc3, 0xa7, 0xea, 0x8e, 0x22, 0x46, 
  0xaf, 0xcb, 0x67, 0x03, 0x4e, 0x2a, 0x86, 0xe2, 0x1c, 0x78, 0xd4, 0xb0, 
  0xfd, 0x99, 0x35, 0x51, 0x96, 0xf2, 0x5e, 0x3a, 0x77, 0x13, 0xbf, 0xdb, 
  0x25, 0x41, 0xed, 0x89, 0xc4, 0xa0, 0x0c, 0x68, 0x81, 0xe5, 0x49, 0x2d, 
  0x60, 0x04, 0xa8, 0xcc, 0x32, 0x56, 0xfa, 0x9e, 0xd3, 0xb7, 0x1b, 0x7f, 
  0xe4, 0x80, 0x2c, 0x48, 0x05, 0x61, 0xcd, 0xa9, 0x57, 0x33, 0x9f, 0xfb, 
  0xb6, 0xd2, 0x7e, 0x1a, 0xf3, 0x97, 0x3b, 0x5f, 0x12, 0x76, 0xda, 0xbe, 
  0x40, 0x24, 0x88, 0xec, 0xa1, 0xc5, 0x69, 0x0d, 0xca, 0xae, 0x02, 0x66, 
  0x2b, 0x4f, 0xe3, 0x87, 0x79, 0x1d, 0xb1, 0xd5, 0x98, 0xfc, 0x50, 0x34, 
  0xdd, 0xb9, 0x15, 0x71, 0x3c, 0x58, 0xf4, 0x90, 0x6e, 0x0a, 0xa6, 0xc2, 
  0x8f, 0xeb, 0x47, 0x23, 
};

static void init_memory(void) {
  wasm_rt_allocate_memory((&w2c_memory), 17, 65536);
  LOAD_DATA(w2c_memory, 1048576u, data_segment_data_0, 268);
}

static void init_table(void) {
  uint32_t offset;
}

/* export: 'memory' */
wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: 'app' */
void (*WASM_RT_ADD_PREFIX(Z_appZ_vv))(void);
/* export: 'DEVICE_PERIPHERALS' */
u32 (*WASM_RT_ADD_PREFIX(Z_DEVICE_PERIPHERALSZ_i));
/* export: '__data_end' */
u32 (*WASM_RT_ADD_PREFIX(Z___data_endZ_i));
/* export: '__heap_base' */
u32 (*WASM_RT_ADD_PREFIX(Z___heap_baseZ_i));

static void init_exports(void) {
  /* export: 'memory' */
  WASM_RT_ADD_PREFIX(Z_memory) = (&w2c_memory);
  /* export: 'app' */
  WASM_RT_ADD_PREFIX(Z_appZ_vv) = (&w2c_app);
  /* export: 'DEVICE_PERIPHERALS' */
  WASM_RT_ADD_PREFIX(Z_DEVICE_PERIPHERALSZ_i) = (&w2c_DEVICE_PERIPHERALS);
  /* export: '__data_end' */
  WASM_RT_ADD_PREFIX(Z___data_endZ_i) = (&w2c___data_end);
  /* export: '__heap_base' */
  WASM_RT_ADD_PREFIX(Z___heap_baseZ_i) = (&w2c___heap_base);
}

void WASM_RT_ADD_PREFIX(init)(void) {
  init_func_types();
  init_globals();
  init_memory();
  init_table();
  init_exports();
}
